### PR TITLE
Partial fix for #64 editable array elements

### PR DESCRIPTION
**Pull request by Octogonapus**
This fixes some of the bug behavior with editing arrays. When making an edit and clicking somewhere else (like on the new element button or a different part of the dialog) the edit is saved; however, if you click on another cell the edit is discarded.
The behavior that discards an edit when you select a different cell is created in the Cell constructor (https://hastebin.com/yepujujipi.java line 21). If we wanted to change this behavior we would have to do some serious reflection. My current guess is that we'd have to use Powermock to mock the Cell constructor so we can change how that listener works.

### CODE REVIEW

**Comment by PeterJohnson** [comment]
I really do think we want to change this behavior.  It's very non-intuitive to use for anyone used to editing cells in something like Excel.

**Comment by PeterJohnson** [comment]
Another minor oddity: The number and string array dialogs can be exited using the Esc key.  This doesn't work in the boolean array dialog for some reason.

**Comment by Octogonapus** [comment]
Are you sure? I just tested and was able to edit all 7 dialog types with the Esc key on Linux.

Edit: Also just tested on Windows and Esc works fine.

**Review by AustinShalit — APPROVED** [review]

**Comment by PeterJohnson** [comment]
I got an exception when trying to update an empty boolean array:
```
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: [Z cannot be cast to [Ljava.lang.Boolean;
        at edu.wpi.first.outlineviewer.controller.MainWindowController.lambda$initialize$3(MainWindowController.java:114)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.control.TreeTableCell.commitEdit(TreeTableCell.java:356)
        at edu.wpi.first.outlineviewer.view.TreeEntryTreeTableCell.commitEdit(TreeEntryTreeTableCell.java:151)
        at edu.wpi.first.outlineviewer.view.TreeEntryTreeTableCell.startEdit(TreeEntryTreeTableCell.java:130)
        at javafx.scene.control.TreeTableCell.updateEditing(TreeTableCell.java:547)
        at javafx.scene.control.TreeTableCell.lambda$new$105(TreeTableCell.java:140)
```

**Comment by Octogonapus** [comment]
I see that as well. Looks like that problem isn't in my code, it's present in the master branch as well.

**Pull request merged**
