### PR TITLE
Add connection indicator

### LINKED ISSUE #3: Provide indicator that NT is connected/disconnected
Maybe change the title of the window?

### PR DESCRIPTION
**Pull request by AustinShalit**
closes #3

### CODE REVIEW

**Review by PeterJohnson — APPROVED** [review]

**Comment by PeterJohnson** [comment]
Due to the way notifications are done it may currently be possible to get a disconnect message before a connect message, which would break the way this does client handling.  However, I think the right fix is to fix ntcore to not do that.

**Comment by ThadHouse** [comment]
Would this cause issues on shutdown, since the listener never gets cleaned up? I think we made ntcore not care about that, but not completely sure.

**Comment by JLLeitschuh** [comment]
Images showing the feature in the PR would be good too.

**Comment by AustinShalit** [comment]
Some photos:
untitled 1
untitled 2
untitled

**Comment by JLLeitschuh** [comment]
LGTM!

**Pull request merged**
