### PR TITLE
Adds a way to set the port for the client

### LINKED ISSUE #6: Add way to select custom port
Would be nice to have, if you want to check the status of a table not running on the standard port.

### PR DESCRIPTION
**Pull request by ThadHouse**
Closes #6

### CODE REVIEW

**Comment by AustinShalit** [comment]
This does not work with IPv6 addresses.  Maybe do something like [this](http://stackoverflow.com/a/2347356)?

**Comment by PeterJohnson** [comment]
We don't support IPv6 yet, but it's not a bad idea to future proof.  Why can't we just create a separate option for the port rather than embedding it in the address?

**Comment by ThadHouse** [comment]
The reason I did it with a colon is I have no clue how javax works, so no real idea how to update the UI. If somebody who knows java UI's wants to do this that would probably be better.

**Comment by SamCarlberg** [comment]
You can use Netbeans' builtin Swing UI designer to modify it, that's what all the `.form` files are for.

**Pull request closed without merging**
