### PR TITLE
Add license

### LINKED ISSUE #25: Missing LICENSE
This project is missing a LICENSE

### PR DESCRIPTION
**Pull request by AustinShalit**
closes #25

### CODE REVIEW

**Review by JLLeitschuh — DISMISSED** [review]

**Comment by PeterJohnson** [comment]
Is there a reason to have the leading asterisks?

**Comment by AustinShalit** [comment]
I did a copy and paste from here: https://github.com/wpilibsuite/allwpilib/blob/master/license.txt

I am not sure why there are asterisks but having them is consistent.

**Comment by PeterJohnson** [comment]
I think they were there because it was copy and pasted from a C++ file.  I removed them from the wpiutil license file, and I think we should do the same with the other repos.

**Comment by AustinShalit** [comment]
Ok

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
