### PR TITLE
Added easier way to use default port

### LINKED ISSUE #46: Easy way to set standard port
There's not obvious way to set the standard port number or documentation of what the standard port number is.  I'm thinking the best approach is to have another slider box for "standard port" in the preferences dialog that enables/disables the port number box.  I think reordering this dialog would also help, to:
 * Server Mode
 * Server Location (was Server ID)
 * Standard Port (new boolean control)
 * Server Port (enabled/disabled by Standard Port control)

### PR DESCRIPTION
**Pull request by Octogonapus**
Added default port switch to PreferencesDialog and redid the dialog to look better. Closes #46

### CODE REVIEW

**Comment by AustinShalit** [comment]
untitled

**Comment by AustinShalit** [comment]
@frcjenkins test this please

**Comment by PeterJohnson** [comment]
@frcjenkins test this please

**Comment by PeterJohnson** [comment]
I'm still not a big fan of "Server ID".  I think I prefer "Server" or "Server Location"?  And can it really accept URLs?

**Comment by Octogonapus** [comment]
Whoops, I forgot to change "Server ID" to "Server Location"...

**Comment by PeterJohnson** [comment]
@frcjenkins retest this please

**Comment by PeterJohnson** [comment]
@frcjenkins retest this please

**Review by AustinShalit — APPROVED** [review]

**Pull request merged**
